messages:
  - "&aWelcome to the server!"
  - "&bRemember to join our Discord!"
  - "&eVote daily for rewards!"
delay: 60       # Delay in seconds between announcements
random: false   # If true, messages are picked randomly; if false, they are in order